In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/Users/kevenlemoing/Sites/Lifesum_application/Data/weight.csv',error_bad_lines=False)

In [4]:
data
#TO DO (about cleaning)
##It's a relational table --> just check the data integrity

        user_id        date  weight_kg
0      24045001  2017-08-30       56.0
1      24547801  2017-08-30       56.0
2      24553601  2017-08-30       58.0
3      24541601  2017-08-30       60.0
4      24542801  2017-08-30       62.0
5      24544401  2017-08-30       62.0
6      24545601  2017-08-30       64.0
7      24551201  2017-08-30       64.0
8      24555001  2017-08-30       68.0
9      24538801  2017-08-30       72.0
10     24553401  2017-08-30       72.0
11     24135801  2017-08-30       76.0
12     24547601  2017-08-30       76.0
13     24537801  2017-08-30       80.0
14     24151601  2017-08-30      100.0
15     24551401  2017-08-30      124.0
16     23373201  2017-08-30       65.0
17     24543601  2017-08-30       65.0
18     24541001  2017-08-30       77.0
19     24554001  2017-08-30       85.0
20     24257201  2017-08-30       89.0
21     24541801  2017-08-30       93.0
22     24544001  2017-08-30       77.5
23     23722401  2017-08-30       93.5
24     24535401  2017-08-30       97.5
25     24540201  2017-08-30       49.0
26     24541401  2017-08-30       55.0
27     24546401  2017-08-30       57.0
28     24551801  2017-08-30       57.0
29     24539601  2017-08-30       59.0
...         ...         ...        ...
11534  23943201  2017-08-29       61.4
11535  23845201  2017-08-29       70.8
11536  24532401  2017-08-29       74.8
11537  24518201  2017-08-29       74.8
11538  24446001  2017-08-29      129.7
11539  24532201  2017-08-29       77.1
11540  24524801  2017-08-29       60.8
11541  24529601  2017-08-29       81.6
11542  24517001  2017-08-29      101.6
11543  24392601  2017-08-29       66.6
11544  24527801  2017-08-29       82.6
11545  24346801  2017-08-29       87.6
11546  24518801  2017-08-29       68.4
11547  23541601  2017-08-29       72.4
11548  24512401  2017-08-29      117.9
11549  24526801  2017-08-29       57.2
11550  23831401  2017-08-29       59.2
11551  24337001  2017-08-29       61.2
11552  24492801  2017-08-29      114.4
11553  23650801  2017-08-29       78.9
11554  24437601  2017-08-29       71.9
11555  24513201  2017-08-29       76.2
11556  24531201  2017-08-29       80.7
11557  23880201  2017-08-29       92.7
11558  24532001  2017-08-29       52.6
11559  24529801  2017-08-29       86.2
11560  23912801  2017-08-29       53.6
11561  24531801  2017-08-29       71.2
11562  24521801  2017-08-29       71.7
11563  24028201  2017-08-29       75.7

[11564 rows x 3 columns]